# Generated by Django 6.1.1 on 2026-09-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_key', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('started', 'Started'), ('approved', 'Approved'), ('declined', 'Declined'), ('paid', 'Paid'), ('verified', 'Verified'), ('blocked', 'Blocked'), ('watching', 'Watching')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField(blank=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('shopping', 'Shopping'), ('travel', 'Travel'), ('reservation', 'Reservation')], max_length=16)),
                ('vendor', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(help_text='Current price in ₹')),
                ('list_price', models.PositiveIntegerField(help_text='Pre-discount price in ₹')),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('facts', models.JSONField(blank=True, default=list)),
                ('cancellation', models.CharField(choices=[('free', 'Free cancellation'), ('paid', 'Paid cancellation'), ('none', 'Non-refundable')], default='free', max_length=8)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated terms used to narrow a goal to this offer', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('auto_pay_enabled', models.BooleanField(default=True)),
                ('auto_approve_limit', models.PositiveIntegerField(default=2000)),
                ('daily_cap', models.PositiveIntegerField(default=25000)),
                ('hard_ceiling', models.PositiveIntegerField(default=100000)),
                ('require_approval_new_vendor', models.BooleanField(default=True)),
                ('require_approval_paid_cancellation', models.BooleanField(default=True)),
                ('trusted_vendors', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'policies',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_key', models.CharField(db_index=True, max_length=64)),
                ('goal_text', models.TextField()),
                ('category', models.CharField(choices=[('shopping', 'Shopping'), ('travel', 'Travel'), ('reservation', 'Reservation')], max_length=16)),
                ('budget', models.PositiveIntegerField()),
                ('min_discount_pct', models.PositiveIntegerField(blank=True, null=True)),
                ('constraints', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('running', 'Running'), ('monitoring', 'Monitoring'), ('awaiting-approval', 'Awaiting approval'), ('completed', 'Completed'), ('declined', 'Declined'), ('blocked', 'Blocked')], default='running', max_length=24)),
                ('stages', models.JSONField(default=list)),
                ('offers', models.JSONField(blank=True, default=list)),
                ('watch', models.JSONField(blank=True, default=list)),
                ('pick_id', models.CharField(blank=True, max_length=32)),
                ('verdict', models.JSONField(blank=True, null=True)),
                ('receipt', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
